<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{7d444f4f-0d00-411e-888e-132e3af9a8ac}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	client : HttpClient;
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[client();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>